"Filed out from Dolphin Smalltalk"!

P3LogEvent subclass: #P3ConnectionClosedEvent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

P3ConnectionClosedEvent guid: (GUID fromString: '{f5cb8530-d447-4027-8051-a583093b4ff7}')!

P3ConnectionClosedEvent comment: 'I am P3ConnectionClosedEvent.I am a P3LogEvent.I represent the closing of PostgreSQL client connection.'!

!P3ConnectionClosedEvent categoriesForClass!P3-Logging! !

!P3ConnectionClosedEvent methodsFor!

printContentsOn: stream		stream print: #Close! !

!P3ConnectionClosedEvent categoriesForMethods!
printContentsOn:!printing!public! !
!

